(() => {
  const $=s=>document.querySelector(s);let data=[],currentAction=null;
  window.selectedCustomer=null;
  window.showToast=text=>{const t=$('#toast');t.textContent=text;t.classList.add('visible');setTimeout(()=>t.classList.remove('visible'),2400)};
  window.updateRiskCounts=counts=>{const map={STABLE:'#side-stable',WATCHLIST:'#side-watch','AT RISK':'#side-risk',CRITICAL:'#side-critical'};Object.entries(map).forEach(([k,s])=>$(s).textContent=counts[k]??0)};
  const pct=x=>`${(Number(x)*100).toFixed(1)}%`;
  const traceSteps=['Customer selected','Churn prediction loaded','Forecast generated','SHAP evidence loaded','Preferences loaded','Eligible actions determined','Recommendation generated'];
  function renderTrace(through=-1){$('#trace').innerHTML=`<div class="trace-heading">EVIDENCE TRACE <span>LIVE</span></div>`+traceSteps.map((label,i)=>`<div class="trace-row ${i<=through?'complete':'pending'}"><i>${i<=through?'✓':'○'}</i> ${label}</div>`).join('')}
  window.renderEvidenceTrace=renderTrace;
  function renderMetrics(m){const el=$('#metrics-grid'),c=m.classification.models,cl=m.clustering,fc=m.forecasting;const cls=Object.entries(c).map(([name,v])=>`<div class="eval-row"><span>${name}</span><b class="${name===m.classification.selected_model?'selected':''}">${name===m.classification.selected_model?'SELECTED':''}</b></div>`).join('');const metrics=[['Precision',v=>v.precision],['Recall',v=>v.recall],['F1',v=>v.f1],['ROC-AUC',v=>v.roc_auc]];const classifier=metrics.map(([n,f])=>`<div class="eval-row"><span>${n}</span><b>${f(c[m.classification.selected_model]).toFixed(3)}</b></div>`).join('');const forecastRows=Object.entries(fc.metrics).map(([n,v])=>`<div class="eval-row"><span>${n==='exp_smoothing'?'Exponential smoothing':'Naive'}</span><b class="${n===fc.selected_model?'selected':''}">${n===fc.selected_model?'SELECTED':''}</b></div><div class="eval-row"><span>MAE · RMSE</span><b>${v.mae.toFixed(1)} · ${v.rmse.toFixed(1)}</b></div>`).join('');el.innerHTML=`<div class="eval-block"><h4>Clustering · ${cl.selected_model}</h4><div class="eval-row"><span>K-Means · silhouette</span><b>${cl.kmeans_silhouette.toFixed(3)}</b></div><div class="eval-row"><span>Clusters · K-Means / DBSCAN</span><b>${cl.kmeans_clusters} / ${cl.dbscan_clusters}</b></div><div class="eval-row"><span>DBSCAN · silhouette</span><b>${cl.dbscan_silhouette==null?'Not defined':cl.dbscan_silhouette.toFixed(3)}</b></div></div><div class="eval-block"><h4>Churn classifier · ${m.classification.selected_model}</h4>${cls}${classifier}<div class="eval-row"><span>Test design</span><b>Customer holdout · ${m.classification.holdout_size}</b></div></div><div class="eval-block"><h4>Forecasting · ${fc.selected_model.replace('_',' ')}</h4>${forecastRows}<div class="eval-row"><span>Validation</span><b>Walk-forward · 3 cutoffs</b></div></div>`}
  function renderShap(s){const max=Math.max(...s.values.map(v=>Math.abs(v.value)),.0001);$('#shap-list').innerHTML=s.values.slice(0,6).map(v=>{const neg=v.value<0,w=Math.max(2,Math.abs(v.value)/max*46);return `<div class="shap-row"><span class="shap-name" title="${v.feature}">${v.label}</span><div class="shap-track"><i class="shap-mid"></i><i class="shap-bar ${neg?'negative':''}" style="width:${w}%;${neg?'right:50%':'left:50%'};transform:${neg?'':'none'}"></i></div><span class="shap-value ${neg?'negative':''}">${v.value>0?'+':''}${v.value.toFixed(3)}</span></div>`}).join('')}
  function renderProfile(p){const fields=[["FAVORITE TOPIC",p.favorite_topic],["CONTENT TYPE",p.preferred_content_type],["MOST USED FEATURE",p.preferred_feature],["STUDY TIME",p.preferred_study_time],["SUBSCRIPTION AGE",`${p.subscription_age_weeks} weeks`],["HISTORICAL ENGAGEMENT",p.historical_engagement_level]];$('#profile-grid').innerHTML=fields.map(([k,v])=>`<div class="profile-item"><small>${k}</small><b>${v}</b></div>`).join('');const selected=window.selectedCustomer;fetch(`/api/customer/${selected}/eligible-actions`).then(r=>r.json()).then(()=>{if(window.selectedCustomer===selected)renderTrace(5)})}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function renderAction(a){currentAction=a.action;$('#action-provider').textContent=a.fallback?'DETERMINISTIC MODE':a.provider.toUpperCase();$('#action-content').innerHTML=`<div class="action-title">${escapeHtml(a.action_label)}<span>· ${escapeHtml(a.action)}</span></div><p class="action-reason">${escapeHtml(a.reason)}</p><div class="action-message">“${escapeHtml(a.message)}”</div>`;$('#execute-action').disabled=false;$('#reject-action').disabled=false}
  window.showRecommendation=renderAction;
  async function selectCustomer(id){if(!CustomerMap.isSegmented())await CustomerMap.segment();window.selectedCustomer=id;currentAction=null;$('#crumb-current').textContent='CUSTOMER WORKSPACE';$('#customer-title').textContent=`Customer ${id}`;$('#context-customer').textContent=id;$('#chat-input').disabled=false;$('#chat-input').placeholder=`Ask about ${id}…`;$('#chat-input').value='';$('#send-chat').disabled=true;$('#action-content').innerHTML='<div class="empty-note">Ask the retention agent “What should we do?” to generate an eligible recommendation.</div>';$('#execute-action').disabled=true;$('#reject-action').disabled=true;$('#action-provider').textContent='AWAITING AGENT';$('#action-toast').textContent='';Chat.reset(id);
    try{const [p,f,s]=await Promise.all([fetch(`/api/customer/${id}`).then(r=>r.json()),fetch(`/api/customer/${id}/forecast`).then(r=>r.json()),fetch(`/api/customer/${id}/explanation`).then(r=>r.json())]);$('#churn-value').innerHTML=`${(p.churn_probability*100).toFixed(1)}<small>%</small>`;$('#risk-label').textContent=`${p.risk} · ${p.segment}`;$('#risk-label').style.color=p.risk==='CRITICAL'?'#ff8d92':p.risk==='STABLE'?'#81d9bd':'#edc27e';$('#usage-change').innerHTML=`${f.expected_change_pct<0?'↓':'↑'} ${Math.abs(f.expected_change_pct).toFixed(0)}<small>%</small>`;$('#usage-change').style.color=f.expected_change_pct<0?'#ff9a88':'#77dfbf';$('#current-usage').innerHTML=`${Math.round(f.current_weekly_usage_minutes)}<small> min</small>`;$('#segment-value').textContent=p.segment;$('#segment-foot').textContent=`Cluster ${p.cluster+1} · behavioral similarity`;$('#forecast-model').textContent=`MODEL · ${f.method.replace('_',' ').toUpperCase()}`;renderShap(s);renderProfile({...p.preferences,subscription_age_weeks:p.features.subscription_age_weeks});ForecastChart.draw(f);$('#compose-note').textContent=`Selected customer · ${id} · evidence loaded`;$('#customer-workspace').scrollIntoView({behavior:'smooth',block:'start'});}catch(e){window.showToast('Could not load customer evidence')}
  }
  async function load(){try{const [res,metrics]=await Promise.all([fetch('/api/customers'),fetch('/api/model-metrics')]);data=await res.json();data=data.map(x=>({...x,risk:null,churn_probability:null}));CustomerMap.init(selectCustomer);CustomerMap.update(data);$('#customer-count').textContent=data.length;$('#demo-customer').innerHTML='<option value="">Choose a customer</option>'+[['C001','C001 · Stable core user'],['C002','C002 · Gradually disengaging'],['C003','C003 · Critical high-risk'],['C004','C004 · Recovering user']].map(([id,l])=>`<option value="${id}">${l}</option>`).join('');$('#demo-customer').addEventListener('change',async e=>{if(e.target.value){if(!CustomerMap.isSegmented())await CustomerMap.segment();if(!CustomerMap.isClassified())await CustomerMap.classify();CustomerMap.select(e.target.value)}});renderMetrics(await metrics.json());document.querySelector('#map-empty').classList.remove('hidden');$('#refresh').addEventListener('click',()=>location.reload());$('#execute-action').addEventListener('click',executeAction);$('#reject-action').addEventListener('click',()=>{currentAction=null;$('#action-provider').textContent='REJECTED';$('#action-content').innerHTML='<div class="empty-note">Recommendation rejected. No action was scheduled.</div>';$('#execute-action').disabled=true;$('#reject-action').disabled=true});Chat.bind();}catch(e){$('#map-subtitle').textContent='Could not connect to the model API. Start the application with python run.py.'}}
  async function executeAction(){if(!currentAction||!window.selectedCustomer)return;try{const r=await fetch(`/api/customer/${window.selectedCustomer}/execute-action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:currentAction})});const x=await r.json();if(!r.ok)throw new Error(x.detail);$('#action-toast').textContent='✓ Action successfully scheduled · simulated';$('#execute-action').disabled=true;window.showToast('Action successfully scheduled · simulation only')}catch(e){$('#action-toast').textContent='Action could not be scheduled: '+e.message}}
  load();
})();
