(() => {
 let history=[],busy=false;
 const body=()=>document.querySelector('#chat-body');
 function pushUser(text){const node=document.createElement('div');node.className='user-bubble';node.textContent=text;body().append(node);body().scrollTop=body().scrollHeight;history.push({role:'user',content:text})}
 function typing(){const node=document.createElement('div');node.className='response-bubble';node.id='typing';node.innerHTML='<div class="agent-small-icon">✳</div><div class="typing"><i></i><i></i><i></i></div>';body().append(node);body().scrollTop=body().scrollHeight}
 function respond(text){document.querySelector('#typing')?.remove();const node=document.createElement('div');node.className='response-bubble';node.innerHTML='<div class="agent-small-icon">✳</div><div class="response-text"></div>';const out=node.querySelector('.response-text');body().append(node);let i=0;const timer=setInterval(()=>{out.textContent+=text.slice(i,i+3);i+=3;body().scrollTop=body().scrollHeight;if(i>=text.length)clearInterval(timer)},8);history.push({role:'assistant',content:text})}
 async function send(text){if(!text.trim()||!window.selectedCustomer||busy)return;busy=true;pushUser(text);typing();document.querySelector('#send-chat').disabled=true;try{const res=await fetch(`/api/customer/${window.selectedCustomer}/chat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:text,conversation:history.slice(0,-1).slice(-8)})});const data=await res.json();document.querySelector('#agent-status').textContent=data.status;respond(data.answer);if(data.recommendation){window.showRecommendation?.(data.recommendation);window.renderEvidenceTrace?.(6)}}catch{respond('The local API could not be reached. Please check that ChurnScope AI is running.')}finally{busy=false;document.querySelector('#send-chat').disabled=false}}
 function reset(customer){history=[];window.renderEvidenceTrace?.(-1);body().innerHTML=`<div class="agent-message"><div class="agent-small-icon">✳</div><div><div class="message-author">RETENTION AGENT <span>· READY</span></div><p>Customer <b>${customer}</b> is selected. I can explain their churn evidence, forecast, preferences, and eligible retention actions.</p></div></div><div class="suggestion-wrap"><small>TRY ASKING</small><button class="suggestion">Why is this customer at risk?</button><button class="suggestion">Show me the evidence</button><button class="suggestion">What should we do?</button><button class="suggestion">Write a personalized message</button></div>`;document.querySelector('#agent-status').textContent='Evidence context loaded';body().querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>send(b.textContent));}
 window.Chat={reset,send,bind(){window.renderEvidenceTrace?.(-1);document.querySelector('#chat-form').addEventListener('submit',e=>{e.preventDefault();const input=document.querySelector('#chat-input');const value=input.value;input.value='';send(value)});document.querySelector('#chat-input').addEventListener('input',e=>{e.currentTarget.style.height='auto';e.currentTarget.style.height=Math.min(90,e.currentTarget.scrollHeight)+'px';document.querySelector('#send-chat').disabled=!e.currentTarget.value.trim()||!window.selectedCustomer});document.querySelectorAll('.suggestion').forEach(b=>b.onclick=()=>send(b.textContent))}};
})();
