(() => {
  const color={"Power Users":"#79dfc1","Core Engaged":"#84c1ad","Fading Engagement":"#e2b66d","Low Activity":"#8b9bae","Irregular Users":"#a996dc"};
  let svg,root,points=[],segmented=false,classified=false,onSelect=()=>{},tooltip;
  const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0};
  function dims(){const el=document.querySelector('.map-stage');return [el.clientWidth,el.clientHeight]}
  function render(){if(!svg)return;const [w,h]=dims();svg.attr('viewBox',`0 0 ${w} ${h}`);if(!points.length)return;
    const ex=d3.extent(points,d=>+d.embedding_x),ey=d3.extent(points,d=>+d.embedding_y);const sx=d3.scaleLinear().domain(ex).range([45,w-35]).nice(),sy=d3.scaleLinear().domain(ey).range([h-35,28]).nice();
    points.forEach(d=>{d.targetX=sx(+d.embedding_x);d.targetY=sy(+d.embedding_y);const seed=hash(d.customer_id);d.startX=35+(seed%10000)/10000*(w-70);d.startY=28+((seed>>>9)%10000)/10000*(h-56)});
    const joined=root.selectAll('g.customer-point').data(points,d=>d.customer_id);joined.exit().remove();const enter=joined.enter().append('g').attr('class','customer-point').attr('transform',d=>`translate(${d.startX},${d.startY})`).style('opacity',0).on('mouseenter',(event,d)=>showTip(event,d)).on('mousemove',(event,d)=>moveTip(event,d)).on('mouseleave',hideTip).on('click',(event,d)=>{event.stopPropagation();select(d.customer_id)});
    enter.append('circle').attr('class','risk-halo').attr('r',5);enter.append('circle').attr('class','point-core').attr('r',d=>3+(hash(d.customer_id)%3)*.24);
    enter.merge(joined).attr('aria-label',d=>`${d.customer_id} ${d.risk||'Unclassified'} ${d.segment}`).attr('class',d=>`customer-point ${d.risk==='STABLE'?'risk-stable':d.risk==='WATCHLIST'?'risk-watch':d.risk==='AT RISK'?'risk-at':d.risk==='CRITICAL'?'risk-critical':''}`).transition().duration(750).style('opacity',1).attr('transform',d=>`translate(${segmented?d.targetX:d.startX},${segmented?d.targetY:d.startY})`);
    if(segmented){const groups=d3.groups(points,d=>d.segment);const labels=root.selectAll('text.cluster-label').data(groups,d=>d[0]);labels.exit().remove();labels.enter().append('text').attr('class','cluster-label').merge(labels).attr('class','cluster-label visible').text(d=>d[0].toUpperCase()).attr('x',d=>d3.mean(d[1],p=>p.targetX)).attr('y',d=>d3.mean(d[1],p=>p.targetY)-15).attr('text-anchor','middle');}
    else root.selectAll('text.cluster-label').remove(); applyFilters();
  }
  function showTip(ev,d){if(!tooltip)return;tooltip.innerHTML=`<b>${d.customer_id}</b><p>Segment <strong>${d.segment||'Not segmented'}</strong></p><p>Risk <strong>${d.risk||'Not classified'}</strong></p><p>Churn <strong>${d.churn_probability==null?'—':(d.churn_probability*100).toFixed(1)+'%'}</strong></p><p>Recent usage <strong>${d.recent_minutes==null?'—':Math.round(d.recent_minutes)+' min/wk'}</strong></p><p>Trend <strong>${d.usage_change_pct==null?'—':(d.usage_change_pct<0?'↓ ':'↑ ')+Math.abs(d.usage_change_pct).toFixed(0)+'%'}</strong></p>`;tooltip.style.display='block';moveTip(ev,d)}
  function moveTip(ev){const rect=document.querySelector('.map-stage').getBoundingClientRect();tooltip.style.left=Math.min(rect.width-180,ev.clientX-rect.left+13)+'px';tooltip.style.top=Math.max(8,ev.clientY-rect.top-8)+'px'}
  function hideTip(){if(tooltip)tooltip.style.display='none'}
  function applyFilters(){if(!root)return;const risk=document.querySelector('#risk-filter')?.value||'ALL',seg=document.querySelector('#segment-filter')?.value||'ALL',sel=window.selectedCustomer;root.selectAll('.customer-point').classed('filtered',d=>(risk!=='ALL'&&d.risk!==risk)||(seg!=='ALL'&&d.segment!==seg)).classed('dimmed',d=>sel&&d.customer_id!==sel).classed('selected',d=>d.customer_id===sel);const visible=points.filter(d=>(risk==='ALL'||d.risk===risk)&&(seg==='ALL'||d.segment===seg));document.querySelector('#filter-count').textContent=(risk==='ALL'&&seg==='ALL')?'Showing all':`Showing ${visible.length}`;document.querySelector('#customer-count').textContent=points.length;}
  function select(id){window.selectedCustomer=id;hideTip();applyFilters();onSelect(id)}
  function update(data){points=data;segmented=false;classified=data.some(d=>d.risk);render();}
  async function segment(){if(!points.length)return;const res=await fetch('/api/segment',{method:'POST'});const body=await res.json();points=body.customers.map(x=>({...x,risk:null,churn_probability:null}));segmented=true;render();document.querySelector('#classify-btn').disabled=false;document.querySelector('#map-empty').classList.add('hidden');document.querySelector('#map-subtitle').textContent='Position = behavioral similarity · ring color = churn-classifier risk';const segs=[...new Set(points.map(x=>x.segment))];const select=document.querySelector('#segment-filter');select.innerHTML='<option value="ALL">All segments</option>'+segs.map(s=>`<option>${s}</option>`).join('');document.querySelector('#cluster-legend').innerHTML=segs.map(s=>`<span><i style="background:${color[s]||'#9aacbd'}"></i>${s}</span>`).join('');window.showToast?.(`${body.clusters} behavior segments identified`)}
  async function classify(){const res=await fetch('/api/classify',{method:'POST'});const body=await res.json();points=body.customers;classified=true;render();window.updateRiskCounts?.(body.counts);window.showToast?.('Churn classification complete · risk overlay added');}
  window.CustomerMap={init(callback){svg=d3.select('#customer-map');root=svg.append('g');tooltip=document.querySelector('#map-tooltip');onSelect=callback;new ResizeObserver(render).observe(document.querySelector('.map-stage'));document.querySelector('#risk-filter').addEventListener('change',applyFilters);document.querySelector('#segment-filter').addEventListener('change',applyFilters);document.querySelector('#segment-btn').addEventListener('click',segment);document.querySelector('#classify-btn').addEventListener('click',classify);},update,select,segment,classify,applyFilters,isSegmented:()=>segmented,isClassified:()=>classified};
})();
